### ISSUE TITLE
GitHub wiki pages support

### ISSUE THREAD

**Issue by williamstark01** [AaronCQL/katex-github-chrome-extension#14]
Hi, does this extension support GitHub wiki pages? If not, would it be possible for this to be added?

**Comment by AaronCQL** [comment]
> Hi, does this extension support GitHub wiki pages? If not, would it be possible for this to be added?

No this does not work on wiki pages, but should be possible to add. Will start working on it.

**Comment by AaronCQL** [comment]
Wiki pages is now supported in `v0.3.5`. Let me know if something isn't working properly. The maths when previewing a wiki page edit isn't rendered for now.

**Comment by williamstark01** [comment]
That was fast! Thanks a lot, works great on wiki pages now.
