### ISSUE TITLE
Feature Request: Add support for Github Issues

### ISSUE THREAD

**Issue by a-lberto** [AaronCQL/katex-github-chrome-extension#20]
It would be very handy if the renderer also worked in GitHub Issues

Example (this should render in this issue)

$e^{i\pi} + 1 = 0$

Thanks for your work, your extension has been very useful to me.

**Comment by jucor** [comment]
This would be tremendous.

**Comment by jucor** [comment]
Pull request submitted in #21 , tested and "seems to work  on my machine" ™️  :)

**Comment by jucor** [comment]
Use-case example: https://github.com/compdemocracy/polis/issues/1289  , where @PaulLessard kindly pointed to this Chrome plugin but where it only helped for the markdown preview, not for the rendering of the issues. PR #21 fixes that :) Thanks @AaronCQL for merging it if suits you :)
