### ISSUE TITLE
Another subscripting issue.

### ISSUE THREAD

**Issue by mathmathniconico** [AaronCQL/katex-github-chrome-extension#3]
Thanks for fixing the issue. You helped me a lot!

And I came across another, but similar bug. So I report this. The sentence below has the same `<em>` tag.

```
$(f_{i})_{\ast}\mathscr{H}\rightarrow f_{i}(z)$
```

**Comment by AaronCQL** [comment]
@mathmathniconico thank you too! You are also helping a lot by reporting these bugs.

I have just pushed a new update with a major change in how the HTML tags are processed. Please allow some time for the extension to update on the Chrome webstore, and let me know if there appears to be any more bugs.
