### ISSUE TITLE
New <em> tag problem.

### ISSUE THREAD

**Issue by mathmathniconico** [AaronCQL/katex-github-chrome-extension#5]
Thank you for your tough work. The last issue was fixed but I noticed some new problems, they might appear from v0.3.1. Below I took examples from my repository. All of them is similar, `<em>` tag, problem. `\mathscr{...}` is problematic?

```
$\bigcap_{\lambda\in\Lambda}\mathscr{F}_{\lambda}$
$(Y_{i}, \mathscr{G}_{i})$
$f_{i}\colon X\rightarrow Y_{i}$
$h^{-1}(f_{i}^{-1}(G_{i}))\in\mathscr{H}$
$(f_{i}\circ h)^{-1}(G_{i})\in\mathscr{H}$
$(\prod Y_{i}, \prod\mathscr{G}_{i})$
$\lbrace g_{ij}\circ f_{i} : i\in I, j\in J_{i} \rbrace$
$V\cap W\in\mathscr{A}_{\neg S}$
$\mathscr{V}\neq\mathscr{U}_{j}$
$\mathscr{U}_{j}$
$U_{j}\in\mathscr{U}_{j}$
$U\in\mathscr{U}_{1}\cap\dotsb\cap\mathscr{U}_{n}\subset\mathscr{V}$
```

**Comment by AaronCQL** [comment]
@mathmathniconico by any chance is this repo of yours public? If so, do you mind sharing the link here? Thanks!

**Comment by mathmathniconico** [comment]
Here. But it's not written in English so you may not be able to read.
https://github.com/mathmathniconico/Notes

Above list can be found in `Notes/ConvergentSpace`
