### ISSUE TITLE
Underscores problem in math expression

### ISSUE THREAD

**Issue by mathmathniconico** [AaronCQL/katex-github-chrome-extension#7]
I encountered new problem.

```
$$
\begin{aligned}
(a/\theta)+_{\theta}(b/\theta) &:=(a+b)/\theta \\
(a/\theta)\cdot_{\theta}(b/\theta) &:=ab/\theta
\end{aligned}
$$
```

This doesn't work. One line is OK. So I think two underscores after `+` and `\cdot` do bad thing.

**Comment by AaronCQL** [comment]
Thanks for the report @mathmathniconico. I might take a little longer for this one; a little caught up with school at the moment 😂
